# Generated by Django 3.0.5 on 2022-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
