# Generated by Django 3.0.5 on 2022-12-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_comment_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pizza',
        ),
    ]
